### ISSUE TITLE
UI Response is slow and blocking

### ISSUE THREAD

**Issue by ssmithstone** [milanboruvka/tunnellij#1]
I've tried the plugin and it looks promising but in the latest stable intellij 13.0.2 it makes the response very unresponsive do i need more memoery allocated ?

**Comment by milanboruvka** [comment]
This plugin is almost 10 years old, but still should work. Please try to uninstall and use the previous version to see if it helps.

**Comment by ssmithstone** [comment]
wow didn't know it was that old
